Create a 1D NumPy array containing numbers from 0 to 9.

In [3]:
import numpy as np

In [4]:
arr1= np.arange(0, 10, dtype=int)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [6]:
arr2 =np.array([3.14, 2.17, 0, 1, 2])
arr2 = arr2.astype(int)
arr2

array([3, 2, 0, 1, 2])

Create a 3x3 NumPy array with values ranging from 1 to 9.

In [8]:
arr3 = np.arange(1,10).reshape(3,3)
arr3 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [11]:
arr4 = np.random.rand(4, 5)
arr4 = np.round(arr4, 2)
arr4

array([[0.48, 0.15, 0.96, 0.71, 0.25],
       [0.48, 0.53, 0.38, 0.23, 0.5 ],
       [0.17, 0.55, 0.51, 0.28, 0.34],
       [0.08, 0.82, 0.2 , 0.86, 0.44]])

Select the second row from a given 2D NumPy array.

In [13]:
second_row = arr4[1]
second_row

array([0.48, 0.53, 0.38, 0.23, 0.5 ])

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [17]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Create a 4x4 identity matrix using NumPy.

In [18]:
arr5 = np.eye(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Find the sum and average of a given 1D array.

In [19]:
np.sum(arr1)

45

In [20]:
np.mean(arr1)

4.5

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [23]:
arr6 = np.arange(1, 21, dtype=int)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
arr7 = arr6.reshape(4, 5)
arr7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Extract all odd numbers from a given NumPy array.

In [27]:
arr8 = arr7[arr7 % 2 != 0]
arr8

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])